run verification directly in this file

diff --git a/.github/workflows/python-to-oas.yml b/.github/workflows/python-to-oas.yml
--- a/.github/workflows/python-to-oas.yml
+++ b/.github/workflows/python-to-oas.yml
@@ -71,22 +71,6 @@ jobs:
 
           echo "OAS_FILES=$OAS_FILES" >> $GITHUB_ENV
 
-      # - name: get oas file names
-      #   run: |
-
-      #     export OAS_FILES=()
-
-      #     IFS=$'\n'
-
-      #     for file in $DECODED_FILES; do
-      #       oas_file="${file%.py}.oas"
-      #       OAS_FILES+=("$oas_file")
-      #     done
-
-      #     echo "oas files; $OAS_FILES"
-
-      #     echo "OAS_FILES=$OAS_FILES" >> $GITHUB_ENV
-
       - name: commit outputted gds/oas files into repository
         run: |
           git config --local user.email jasminabrar@users.noreply.github.com
@@ -97,8 +81,64 @@ jobs:
             git add "submissions/$file"
           done
 
-          git commit -m "Add oas files produced from .py files"      
-          git push    
+          git commit -m "Add oas files produced from .py files" 
+          git push
 
+      - name: run verification
+        run: |
+          # print the names of the files
+          echo "Files for verification: $OAS_FILES"
+
+          files_with_errors=""
+
+          IFS=' '
+        
+          # run verification on all files
+          for file in $OAS_FILES; do
+
+            echo "Running verification on $file"
+
+            output=$(python run_verification.py "submissions/$file")
+
+            # get number of errors
+            errors_from_output=$(echo "$output" | tail -n 1)
+
+            echo "$errors_from_output errors detected for $file"
+
+            # if file results in verification errors add to string files_with_errors
+            if [[ "$errors_from_output" -ge 1 ]]; then
+              files_with_errors+="$file, $errors_from_output errors. "
+            fi
+
+            echo "Done verification on $file"
+          done
+
+          echo "files_with_errors=$files_with_errors" >> $GITHUB_ENV
+        
+      - name: move output files to new folder
+        run: |
+          export OUTPUT_FILES=$(find /home/runner/work/openEBL-2024-02/openEBL-2024-02/submissions -name "*.lyrdb")
+          echo "Output files: $OUTPUT_FILES"
+
+          mkdir -p verification_output
+
+          for file in $OUTPUT_FILES; do
+            cp "$file" verification_output/
+          done
+
+      - name: upload artifact
+        uses: actions/upload-artifact@v2
+        with:
+          name: layout-errors
+          path: verification_output/
+
+      - name: fail if there are errors from layout verification
+        run: |
+          if [ -z "$files_with_errors" ]; then
+            echo "No errors detected."
+          else
+            echo "Errors detected: $files_with_errors"
+            exit 1
+          fi
 
 
